### ISSUE TITLE
Start a discord / slack / zulip / gitter / whatever 

### ISSUE THREAD

**Issue by Tko1** [Tko1/ClojureRS#25]
For now I'm just putting together a discord, as I've always preferred its feature-set. That being said, I'm open to whatever works best for the most people 

@scileo do you have a discord? 

Link here: https://discord.gg/aS5Sa8p

**Comment by scileo** [comment]
Sure, I have joined the server

**Comment by scileo** [comment]
Perhaps a link to this discord server should be included in the `readme.org` file, so that future contributors can reach us easily.
