### ISSUE TITLE
Discuss collaboration with Claire author 

### ISSUE THREAD

**Issue by Tko1** [Tko1/ClojureRS#3]
> Hi there !
> 
> I don't know if it's the right place, if not I'm sorry. I also just came across your project which seems really cool and of special interest to me.
> 
> I got the same idea about implementing Clojure in Rust and I have been working on a Clojure implementation of my own in the last few weeks. It is not as advanced as yours (I mostly only have the parser part so far) and I have only used the standard library. You want to take a look you can find it at https://github.com/arbroween/claire
> 
> Would you be interested to collaborate or take contributors ? :)

_Originally posted by @arbroween in https://github.com/Tko1/ClojureRS/issues/1#issuecomment-618359949_

**Comment by Tko1** [comment]
@arbroween hey there, I'd love to talk. You can email me at zdot101@gmail.com,  or find me on the clojure slack as cameron.  Let me know if you need some other method of contacting me, and I'll close this issue once you do

**Comment by arbroween** [comment]
Sorry for posting it there then 😅

Great ! I look forward to talking with you. As I currently don't have slack I'll send you an email :)

**Comment by Tko1** [comment]
No worries at all!
