### ISSUE TITLE
Rewrite parsers, and readers, to take &str instead of &[u8] 

### ISSUE THREAD

**Issue by Tko1** [Tko1/ClojureRS#5]
_File affected: reader.rs_

**Comment by Tko1** [comment]
> If you're okay with it, then I'll be very happy to implement it!
> 
> That was supposed to be my next comment, by the way.

Late comment; anyways, @scileo I've added you to this issue then, as always I appreciate all the help and let me know if you have any issue!

**Comment by scileo** [comment]
I appreciate it. I'll start working on it tomorrow, and I'll keep you informed of my position.
