### ISSUE TITLE
Add unit tests for reader.rs

### ISSUE THREAD

**Issue by Tko1** [Tko1/ClojureRS#7]

**Comment by erkkikeranen** [comment]
Hi, interesting project you have. I write Clojure at my day job but I am also interested in Rust. 

I would like to give this issue a try. 

Any comments on the way I propose to add some initial trivial tests? 
https://github.com/erkkikeranen/ClojureRS/blob/reader-unit-test/src/reader.rs

**Comment by Tko1** [comment]
Hey there, glad to see you here!

>I write Clojure at my day job

Very awesome, I am jealous aha. I'd be very interested in hearing about what you do there

So far it does not seem to be so, you got all edge cases with consuming whitespace I can think of, as well as the general case.  Let me know if you need any help with anything

**Comment by erkkikeranen** [comment]
does this issue require more coverage, or is there enough examples to add tests?

**Comment by Tko1** [comment]
It looks like you got them all, I'm gonna close this one
